### PR TITLE
Fix: Skip Argument is Failing in L10

### LINKED ISSUE #1078: Bug: Skip argv is no longer working in laravel 10
Versions: 

Package: 6.0
Laravel: 10.8.0

Problem:

Skip is no longer working, the command is using in_array comparision, but the haystack is a single item array of all skip items.

Suggest using 

```php

if ($this->option('skip')) {
            return in_array($skip, explode(",", $this->option('skip') ?? '') );
        }

        return false;

```

Ugly but see this DD for more clarity.

image

image

### PR DESCRIPTION
**Pull request by robertmarney**
Closes #1078

### CODE REVIEW

File: src/Commands/BaseCommand.php [hunk 1]
```diff
@@ -186,7 +186,7 @@ public function runMigration(): bool
     public function isSkip($skip): bool
     {
         if ($this->option('skip')) {
-            return in_array($skip, (array) $this->option('skip'));
+            return in_array($skip, explode(",", $this->option('skip') ?? '') );
```
Comment (robertmarney) [inline src/Commands/BaseCommand.php]:
```suggestion
            return in_array($skip, explode(',', $this->option('skip') ?? ''));
```

**Comment by mitulgolakiya** [comment]
Good catch @robertmarney .
